export default {
  language: { label: "Language", zhCN: "简体中文", zhHK: "繁體中文", enUS: "English" },
  nav: { ask: "Ask", explore: "Explore", admin: "Admin", search: "Search", toggleTheme: "Toggle theme" },
  ask: { eyebrow: "ANONYMOUS QUESTION", defaultTitle: "What would you like to ask?", description: "Write your question here.", nickname: "Nickname (optional)", content: "What would you like to ask?", attachment: "Image attachment (optional)", imageTooLarge: "The image must be no larger than {size} KB", submit: "Send question", submitted: "Your question has been sent to the inbox. Thanks for asking!", failed: "Unable to send question" },
  explore: { eyebrow: "PUBLIC EXPLORE", title: "Explore answers", description: "Browse answered questions shared publicly.", empty: "There are no public answers yet." },
  search: { eyebrow: "PUBLIC SEARCH", title: "Search questions", placeholder: "Enter keywords to search…", empty: "No questions found." },
  question: { anonymous: "Anonymous", askedAt: "{name} asked on {time}", answeredAt: "Answered on {time}", unanswered: "Not answered yet", attachmentAlt: "Question attachment" },
  admin: { eyebrow: "ADMIN", title: "Manage your inbox", loginDescription: "Sign in to review questions and manage public answers.", username: "Username", password: "Password", login: "Sign in", loginFailed: "Sign-in failed", menuTitle: "What would you like to manage?", menuDescription: "Choose a task to get started.", questions: "Questions", questionsDescription: "View, answer, publish, or delete received questions", settings: "Custom settings", settingsDescription: "Personalize the site's content and appearance", dashboard: "Dashboard", allQuestions: "All questions", pendingQuestions: "Pending", sessions: "Sessions", sessionsDescription: "Revoke device sign-ins you no longer use. Revoking this session signs you out immediately.", session: "Signed-in device", currentSession: "This device", sessionExpires: "Expires {time}", revoke: "Revoke", noSessions: "There are no active sessions.", sessionRevokeFailed: "Unable to revoke session" },
  inbox: { eyebrow: "INBOX", title: "Questions", description: "Review received questions. You can publish an answer after saving it.", pending: "Pending", answered: "Answered", published: "Published", all: "All", answer: "Answer", publish: "Publish to homepage", save: "Save answer", saved: "Answer saved.", empty: "There are no questions here yet.", loadFailed: "Unable to load questions", saveFailed: "Unable to save answer" },
  settings: { eyebrow: "SITE APPEARANCE", title: "Custom settings", description: "Adjust the appearance and attribution of public pages.", basics: "Basic content", theme: "Theme", security: "Security", securityDescription: "Manage your password and signed-in devices.", sessions: "Sessions", sessionsDescription: "Manage signed-in devices", session: "Signed-in device", currentSession: "This device", sessionCreated: "Created {time}", sessionExpires: "Expires {time}", revoke: "Revoke", noSessions: "There are no active sessions.", loadingSessions: "Loading sessions…", sessionsLoadFailed: "Unable to load sessions", sessionRevokeFailed: "Unable to revoke session", resetPassword: "Reset password", resetPasswordDescription: "Enter your current and new passwords. All devices will be signed out when it is complete.", currentPassword: "Current password", newPassword: "New password", resettingPassword: "Resetting…", passwordResetSuccess: "Password reset. All sign-in sessions have been revoked; use your new password to sign in.", passwordResetFailed: "Unable to reset password", siteName: "Site name", copyrightName: "Copyright name", maxUploadKB: "Maximum image upload (KB)", primaryColor: "Primary color", cardOpacity: "Card opacity: {value}%", save: "Save settings", saved: "Settings saved.", loadFailed: "Unable to load settings", saveFailed: "Unable to save settings" },
  error: { requestFailed: "Request failed" },
} as const;
